"""按业务接口组组织的 Pydantic schema 兼容入口。"""

from .common import (
    IntentType,
    SubIntentType,
    SSEEvent,
    IntentResult,
)

from .chat import ChatRequest, ChatResponse

from .knowledge import KnowledgeResult, KnowledgeSearchRequest, KnowledgeSearchResponse

from .health_quadrant import (
    HealthQuadrantSingleExamItem,
    HealthQuadrantRequest,
    HealthQuadrantBucket,
    HealthQuadrantResponse,
    HealthQuadrantConfirmRequest,
    HealthQuadrantConfirmResponse,
    HealthQuadrantQueryEnvelopeResponse,
    HealthQuadrantConfirmEnvelopeResponse,
)

from .smart_meal import (
    SmartMealMealType,
    SmartMealRiskIdentifyRequest,
    SmartMealRiskItem,
    SmartMealRiskIdentifyEnvelopeResponse,
    SmartMealPackageRecommendRequest,
    SmartMealPackageRecommendItem,
    SmartMealPackageRecommendEnvelopeResponse,
)

from .report_intent import ReportIntentDialogRequest, ReportIntentDialogData, ReportIntentDialogEnvelopeResponse

from .transcript_extract import TranscriptExtractRequest, TranscriptExtractData, TranscriptExtractEnvelopeResponse

from .api_query import (
    ApiQueryRequest,
    ApiQueryBusinessIntent,
    ApiQueryExecutionStatus,
    ApiQueryRoutingResult,
    ApiQueryPlanStep,
    ApiQueryExecutionPlan,
    ApiQueryExecutionResult,
    ApiQueryExecutionErrorDetail,
    ApiQueryContextStepResult,
    ApiQueryUIAction,
    ApiQueryDetailRequestRuntime,
    ApiQueryDetailSourceRuntime,
    ApiQueryDetailRuntime,
    ApiQueryListPaginationRuntime,
    ApiQueryListFilterFieldRuntime,
    ApiQueryListTableFieldRuntime,
    ApiQueryListFiltersRuntime,
    ApiQueryListQueryContextRuntime,
    ApiQueryListRuntime,
    ApiQueryFormOptionSourceRuntime,
    ApiQueryFormFieldRuntime,
    ApiQueryFormSubmitRuntime,
    ApiQueryFormRuntime,
    ApiQueryAuditRuntime,
    ApiQueryUIRuntime,
    ApiQueryRuntimeMetadataResponse,
    ApiQueryResponse,
)

from .catalog_governance import (
    ApiCatalogIndexJobStatus,
    ApiCatalogIndexJobResponse,
    ApiCatalogGovernanceJobStatus,
    SemanticCurationPhase,
    SemanticCurationMode,
    SemanticCurationRunStatus,
    ApiCatalogIncrementalGovernanceRequest,
    ApiCatalogColdStartGovernanceRequest,
    ApiCatalogGovernanceJobResponse,
    ApiCatalogGovernanceRunResponse,
    ApiCatalogGovernancePromoteRequest,
    ApiCatalogGovernanceRollbackRequest,
)

from .text2sql import (
    QueryDomain,
    Text2SQLRequest,
    Text2SQLResponse,
    TrainItem,
    TrainRequest,
    TrainResponse,
)

from .health import HealthResponse

__all__ = [
    "IntentType",
    "SubIntentType",
    "SSEEvent",
    "IntentResult",
    "ChatRequest",
    "ChatResponse",
    "KnowledgeResult",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "HealthQuadrantSingleExamItem",
    "HealthQuadrantRequest",
    "HealthQuadrantBucket",
    "HealthQuadrantResponse",
    "HealthQuadrantConfirmRequest",
    "HealthQuadrantConfirmResponse",
    "HealthQuadrantQueryEnvelopeResponse",
    "HealthQuadrantConfirmEnvelopeResponse",
    "SmartMealMealType",
    "SmartMealRiskIdentifyRequest",
    "SmartMealRiskItem",
    "SmartMealRiskIdentifyEnvelopeResponse",
    "SmartMealPackageRecommendRequest",
    "SmartMealPackageRecommendItem",
    "SmartMealPackageRecommendEnvelopeResponse",
    "ReportIntentDialogRequest",
    "ReportIntentDialogData",
    "ReportIntentDialogEnvelopeResponse",
    "TranscriptExtractRequest",
    "TranscriptExtractData",
    "TranscriptExtractEnvelopeResponse",
    "ApiQueryRequest",
    "ApiQueryBusinessIntent",
    "ApiQueryExecutionStatus",
    "ApiQueryRoutingResult",
    "ApiQueryPlanStep",
    "ApiQueryExecutionPlan",
    "ApiQueryExecutionResult",
    "ApiQueryExecutionErrorDetail",
    "ApiQueryContextStepResult",
    "ApiQueryUIAction",
    "ApiQueryDetailRequestRuntime",
    "ApiQueryDetailSourceRuntime",
    "ApiQueryDetailRuntime",
    "ApiQueryListPaginationRuntime",
    "ApiQueryListFilterFieldRuntime",
    "ApiQueryListTableFieldRuntime",
    "ApiQueryListFiltersRuntime",
    "ApiQueryListQueryContextRuntime",
    "ApiQueryListRuntime",
    "ApiQueryFormOptionSourceRuntime",
    "ApiQueryFormFieldRuntime",
    "ApiQueryFormSubmitRuntime",
    "ApiQueryFormRuntime",
    "ApiQueryAuditRuntime",
    "ApiQueryUIRuntime",
    "ApiQueryRuntimeMetadataResponse",
    "ApiQueryResponse",
    "ApiCatalogIndexJobStatus",
    "ApiCatalogIndexJobResponse",
    "ApiCatalogGovernanceJobStatus",
    "SemanticCurationPhase",
    "SemanticCurationMode",
    "SemanticCurationRunStatus",
    "ApiCatalogIncrementalGovernanceRequest",
    "ApiCatalogColdStartGovernanceRequest",
    "ApiCatalogGovernanceJobResponse",
    "ApiCatalogGovernanceRunResponse",
    "ApiCatalogGovernancePromoteRequest",
    "ApiCatalogGovernanceRollbackRequest",
    "QueryDomain",
    "Text2SQLRequest",
    "Text2SQLResponse",
    "TrainItem",
    "TrainRequest",
    "TrainResponse",
    "HealthResponse",
]
