#!/bin/sh
set -eu

BUSINESS_DB="${BUSINESS_MYSQL_DATABASE:-ai_platform_business}"
AI_DB="${AI_MYSQL_DATABASE:-ai_platform_gateway}"
APP_USER="${BUSINESS_MYSQL_USER:-ai_platform}"
APP_PASSWORD="${BUSINESS_MYSQL_PASSWORD:-ai_platform_dev}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
CREATE DATABASE IF NOT EXISTS \`${BUSINESS_DB}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS \`${AI_DB}\`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';
ALTER USER '${APP_USER}'@'%' IDENTIFIED BY '${APP_PASSWORD}';

GRANT ALL PRIVILEGES ON \`${BUSINESS_DB}\`.* TO '${APP_USER}'@'%';
GRANT ALL PRIVILEGES ON \`${AI_DB}\`.* TO '${APP_USER}'@'%';
FLUSH PRIVILEGES;
EOSQL
