server:
  port: 8080

spring:
  application:
    name: ai-business-server
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      timeout: 5000

  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_uuid
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
