CREATE TABLE IF NOT EXISTS `function_medicine_ai_mapping` (
  `id` varchar(64) NOT NULL COMMENT '主键',
  `serial_no` int DEFAULT NULL COMMENT 'Excel 序号',
  `system_name` varchar(128) DEFAULT NULL COMMENT '所属系统',
  `project_name` varchar(255) NOT NULL COMMENT '项目名称',
  `indicator_code` varchar(64) DEFAULT NULL COMMENT '指标代码',
  `indicator_name` varchar(255) DEFAULT NULL COMMENT '指标名称',
  `exam_project_name` varchar(255) DEFAULT NULL COMMENT '所属检查项目名称',
  `ideal_range` varchar(255) DEFAULT NULL COMMENT '理想值范围',
  `package_version` varchar(128) DEFAULT NULL COMMENT '套餐/版本',
  `price_text` varchar(64) DEFAULT NULL COMMENT '价格原始文本',
  `core_effect` text COMMENT '核心功效',
  `indications` text COMMENT '适应症',
  `contraindications` text COMMENT '禁忌症(风险)',
  `remark` text COMMENT '备注',
  `status` varchar(32) NOT NULL DEFAULT 'active' COMMENT '状态',
  `source_sheet_name` varchar(128) DEFAULT NULL COMMENT '来源 sheet',
  `source_row_no` int DEFAULT NULL COMMENT '来源 Excel 行号',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_function_medicine_ai_mapping_system` (`system_name`),
  KEY `idx_function_medicine_ai_mapping_project` (`project_name`),
  KEY `idx_function_medicine_ai_mapping_package` (`package_version`),
  KEY `idx_function_medicine_ai_mapping_indicator_code` (`indicator_code`),
  KEY `idx_function_medicine_ai_mapping_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='功能医学AI推荐方案映射表';
